import { motion } from "framer-motion";
import {
  AlertTriangle,
  Activity,
  HeartPulse,
  CheckCircle2,
  Clipboard,
  Download,
  MapPin,
  ShieldAlert,
  Home,
  Stethoscope,
} from "lucide-react";

import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";

export default function TriageCard({ result }) {
  if (!result) return null;

  const urgency =
    result.urgency ||
    result.severity ||
    result.level ||
    "Routine";

  const confidence = Number(result.confidence ?? 75);

  const symptoms = result.symptoms || [];

  const recommendation =
    result.recommendation || "No recommendation provided.";

  const followUp =
    result.follow_up_questions ||
    result.followUpQuestions ||
    [];

  const disclaimer =
    result.disclaimer ||
    "This AI provides informational assistance only and is not a substitute for professional medical advice.";

  const urgencyConfig = {
    "Self Care": {
      color: "bg-green-600 text-white",
      icon: <Home className="h-5 w-5" />,
      title: "Self Care",
      description:
        "Your symptoms appear mild. Home care, rest, hydration, and monitoring are generally appropriate.",
    },

    Routine: {
      color: "bg-blue-600 text-white",
      icon: <Stethoscope className="h-5 w-5" />,
      title: "Routine",
      description:
        "A routine consultation with a healthcare professional is recommended within the next few days.",
    },

    Urgent: {
      color: "bg-orange-500 text-white",
      icon: <AlertTriangle className="h-5 w-5" />,
      title: "Urgent",
      description:
        "Your symptoms may require medical attention today. Please seek care as soon as possible.",
    },

    Emergency: {
      color: "bg-red-600 text-white",
      icon: <AlertTriangle className="h-5 w-5" />,
      title: "Emergency",
      description:
        "Your symptoms may indicate a medical emergency. Seek immediate medical attention.",
    },
  };

  const current =
    urgencyConfig[urgency] ||
    urgencyConfig["Routine"];

  function copyResult() {
    navigator.clipboard.writeText(
      JSON.stringify(result, null, 2)
    );

    toast.success("Copied to clipboard");
  }

  function downloadJSON() {
    const blob = new Blob(
      [JSON.stringify(result, null, 2)],
      {
        type: "application/json",
      }
    );

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = "health-report.json";

    a.click();

    URL.revokeObjectURL(url);

    toast.success("Downloaded");
  }

  function openHospital() {
    window.open(
      "https://www.google.com/maps/search/hospital+near+me",
      "_blank"
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
      className="space-y-6"
    >
      {/* Header */}

      <Card className="p-6">
        <div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
          <div className="flex items-center gap-4">
            <div className="rounded-2xl bg-primary/10 p-4">
              <HeartPulse className="h-7 w-7 text-primary" />
            </div>

            <div>
              <h2 className="text-2xl font-bold">
                AI Triage Result
              </h2>

              <p className="text-muted-foreground">
                Generated by Gemma 4
              </p>
            </div>
          </div>

          <Badge
            className={`${current.color} px-5 py-2 text-base flex items-center gap-2`}
          >
            {current.icon}
            {current.title}
          </Badge>
        </div>

        <Separator className="my-6" />

        <Card className="border-l-4 border-primary bg-muted/30 p-4">
          <h3 className="font-semibold text-lg">
            {current.title}
          </h3>

          <p className="mt-2 text-muted-foreground leading-7">
            {current.description}
          </p>
        </Card>

        <div className="mt-6 space-y-3">
          <div className="flex justify-between">
            <span className="font-medium">
              Confidence
            </span>

            <span>{confidence}%</span>
          </div>

          <Progress value={confidence} />
        </div>
      </Card>

      {/* Symptoms */}

      <Card className="p-6">
        <div className="flex items-center gap-3">
          <Activity className="text-primary" />

          <h3 className="text-xl font-semibold">
            Symptoms Identified
          </h3>
        </div>

        <div className="mt-5 flex flex-wrap gap-3">
          {symptoms.length ? (
            symptoms.map((item, index) => (
              <Badge
                key={index}
                variant="secondary"
                className="rounded-full px-4 py-2"
              >
                {item}
              </Badge>
            ))
          ) : (
            <p className="text-muted-foreground">
              No symptoms extracted.
            </p>
          )}
        </div>
      </Card>

      {/* Recommendation */}

      <Card className="p-6">
        <div className="flex items-center gap-3">
          <CheckCircle2 className="text-green-600" />

          <h3 className="text-xl font-semibold">
            Recommendation
          </h3>
        </div>

        <p className="mt-5 leading-8 text-muted-foreground">
          {recommendation}
        </p>
      </Card>

      {/* Follow-up */}

      {followUp.length > 0 && (
        <Card className="p-6">
          <h3 className="text-xl font-semibold mb-4">
            Follow-up Questions
          </h3>

          <ul className="list-disc pl-6 space-y-2">
            {followUp.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </Card>
      )}

      {/* Disclaimer */}

      <Card className="border-yellow-300 bg-yellow-50 p-6">
        <div className="flex items-start gap-4">
          <ShieldAlert className="mt-1 text-yellow-600" />

          <div>
            <h3 className="font-semibold">
              Medical Disclaimer
            </h3>

            <p className="mt-2 text-sm leading-7 text-slate-700">
              {disclaimer}
            </p>
          </div>
        </div>
      </Card>

      {/* Actions */}

      <div className="flex flex-wrap gap-4">
        <Button variant="outline" onClick={copyResult}>
          <Clipboard className="mr-2 h-4 w-4" />
          Copy
        </Button>

        <Button variant="outline" onClick={downloadJSON}>
          <Download className="mr-2 h-4 w-4" />
          Download JSON
        </Button>

        <Button onClick={openHospital}>
          <MapPin className="mr-2 h-4 w-4" />
          Nearby Hospitals
        </Button>
      </div>

      {urgency === "Emergency" && (
        <motion.div
          initial={{ scale: 0.9 }}
          animate={{ scale: 1 }}
        >
          <Card className="border-red-600 bg-red-50 p-6">
            <div className="flex gap-4">
              <AlertTriangle className="text-red-600" />

              <div>
                <h3 className="font-bold text-red-700">
                  Emergency Detected
                </h3>

                <p className="mt-2 leading-7 text-red-700">
                  Your symptoms may require immediate medical attention. Please
                  contact your local emergency services or visit the nearest
                  emergency department immediately.
                </p>
              </div>
            </div>
          </Card>
        </motion.div>
      )}
    </motion.div>
  );
}